e_platform/communication/urls.py
from django.urls import path

from .import views
app_name='communication'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/', views.detail,name='detail'),
    path('new/<int:item_pk>/',views.new_conversation,name='new')
]

e_platform/e_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
     path('dashboard/',include('dashboard.urls')),
    path('',include('core_app.urls')),
    path('inbox/',include('communication.urls')),
    path('items/',include('items.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_platform/items/urls.py
from django.urls import path
from .import views

app_name='item'
urlpatterns = [
    path('',views.items_b,name='items_b'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    
]

e_platform/items/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=255)

    class Meta:
        ordering=('name',)
        verbose_name_plural='Categories'

    def __str__(self):
        return self.name
    
class item(models.Model):
    category=models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    description=models.TextField(blank=True,null=True)
    price=models.FloatField()
    image=models.ImageField(upload_to='item_image',blank=True,null=True)
    is_available=models.BooleanField(default=True)
    created_by=models.ForeignKey(User,related_name='items',on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

e_platform/items/forms.py
from django import forms
from .models import item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = item
        fields = ('category', 'name', 'description', 'price', 'image')
        widgets = {
            'category': forms.Select(attrs={'class': 'form-select', 'style': 'background-color: #BED0FA;'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #BED0FA;'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'style': 'background-color: #BED0FA;'}),
            'price': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #BED0FA;'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'style': 'background-color: #BED0FA;'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control col-md-6'})

class EditItemForm(forms.ModelForm):
    class Meta:
        model = item
        fields = ('name', 'description', 'price', 'image','is_available')
        widgets = {
            
            'name': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #BED0FA;'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'style': 'background-color: #BED0FA;'}),
            'price': forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: #BED0FA;'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'style': 'background-color: #BED0FA;'}),
           
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control col-md-6'})

e_platform/items/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .models import item,Category
from django.db.models import Q
from .forms import NewItemForm,EditItemForm

# Create your views here.
def items_b(request):
    query=request.GET.get('query','')
    category_id=request.GET.get('category',0)

    categories=Category.objects.all()
    items=item.objects.filter(is_available=True)
    if category_id:
        items=items.filter(category_id=category_id)
    if query:
        items=items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'item/item.html',{'items':items,'query':query,
                                            'categories':categories,
                                            'category_id':category_id})



def detail(request,pk):
    items=get_object_or_404(item,pk=pk)
    related_items=item.objects.filter(category=items.category,is_available=True).exclude(pk=pk)[0:3]
    return render(request,'item/detail.html',{'item':items,'related_items':related_items})

@login_required
def new(request):
    if request.method=='POST':
        form=NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item=form.save(commit=False)
            item.created_by=request.user
            item.save()
            return redirect('item:detail',pk=item.id)
    else:

        form=NewItemForm()
    return render(request,'item/form.html',{'form':form,'title':'New Item'})

@login_required
def delete(request,pk):
    Item=get_object_or_404(item,pk=pk,created_by=request.user)
    Item.delete()
    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    Item = get_object_or_404(item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=Item)  # Corrected 'Item' to have a capital 'I'
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=Item.id)  # Corrected 'Item' to have a capital 'I'
    else:
        form = EditItemForm(instance=Item)
    return render(request, 'item/form.html', {'form': form, 'title': 'Edit Item'})

e_platform/items/templates/item/detail.html
{% extends 'core_app/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.image.url }}" class="img-fluid rounded dec_div" alt="{{ item.name }}">
        </div>
        <div class="col-md-6">
            <div class=" p-4 rounded dec_div" style="background-color:#EEEDDA">
                <h1 class="mb-4">{{ item.name }}</h1>
                <p class="text-muted"><strong>Price:</strong> ${{ item.price }}</p>
                {% if item.description %}
                    <p class="text-muted"><strong>Description:</strong> {{ item.description }}</p>
                {% endif %}
                {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl shadow">
                    
                    <p class="mb-4 ml-3">This is Your Item!</p>
                    <a href="{% url 'item:edit' item.id %}" class="btn btn-success mb-3 ml-3">
                        <i class="bi bi-trash"></i> Edit
                    </a>
                    <a href="{% url 'item:delete' item.id %}" class="btn btn-danger mb-3 ml-3">
                        <i class="bi bi-trash"></i> Delete
                    </a>
                </div>
                
                    
                        
                {% else %}

                    <p class="text-muted"><strong>Seller:</strong> {{ item.created_by.username }}</p>
                    <a href="{% url 'communication:new' item.id %}" class="btn btn-primary">Contact Seller</a>
                 {% endif%}   
            </div>
        </div>
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-light rounded-xl" style="background-color:#E2DE99">
    <h2 class="mb-4 text-center display-4 border border-3 rounded " style="background-color:#EAE842" >Related Items</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4 rounded" style="background-color:#EAE842" name="div1">
        {% for item in related_items %}
            <div class="col">
                <a href="{% url 'item:detail' item.id %}">
                    <div class="card h-100 border-0 shadow-sm" style="background-color:#CDE45A">
                        <img src="{{ item.image.url }}" class="card-img-top rounded-top" name="rel_img" alt="{{ item.name }}" style="width:300px; height: 300px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.name }}</h5>
                            <p class="card-text text-muted">Price: {{ item.price }}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

<style>
    .dec_div:hover {
        box-shadow: 0 8px 10px rgba(0, 0, 0, 0.4);
    }
</style>

{% endblock %}

e_platform/items/templates/item/form.html
{% extends 'core_app/base.html' %}
{% block title %}{{title}}{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mb-6 text-3xl">{{title}}</h1>
  <form method="POST" action="." enctype="multipart/form-data" class="mx-auto">
    {% csrf_token %}
    <div class="space-y-4">
        {{form.as_p}}
    </div>
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
          {{field.errors}}
          {% endfor %}
          {{form.non_field_errors}}
    </div>
    {% endif %}
    <button type="submit" class="btn btn-primary mt-4" style="width: 150px;">Submit</button>
  </form>
</div>
<div class="mb-4"></div>
{% endblock %}

e_platform/items/templates/item/item.html
{% extends 'core_app/base.html' %}
{% block title%}Items{% endblock %}

{% block content%}
<div class="container py-6">
    <div class="row">
        <div class="col-md-3">
            <form method="get" action="{% url 'item:items_b' %}">
                <div class="input-group mb-3">
                    <input name="query" type="text" class="form-control" value="{{query}}" placeholder="Find a bike, a chair, or a car....">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
            <hr class="my-6">
            <p class="semi-bold">Categories</p>
            <ul>
                {% for category in categories %}
                <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif %}">
                    <a href='{% url 'item:items_b' %}?query={{query}}&category={{category.id}}'>{{category.name}}</a>
                </li>
                {% endfor %}
            </ul>
            <hr class="my-6">
            <p class="semi-bold">
                <a href="{% url 'item:items_b' %}" class="btn btn-warning btn-block">Clear Filters</a>
            </p>
        </div>
        <div class="col-span-3">
            <div class="row row-cols-1 row-cols-md-3 g-4 rounded" style="background-color:#EAE842" name="div1">
                {% for item in items %}
                <div class="col">
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="card h-100 border-0 shadow-sm" style="background-color:#CDE45A">
                            <img src="{{ item.image.url }}" class="card-img-top rounded-top" alt="{{ item.name }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.name |slice:":12" }}{% if item.name|length > 12 %}...{% endif %}</h5>
                                <p class="card-text text-muted">Price: {{ item.price }}</p>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}