e_platform/communication/urls.py
from django.urls import path

from .import views
app_name='communication'

urlpatterns = [
    path('',views.inbox,name='inbox'),
    path('<int:pk>/', views.detail,name='detail'),
    path('new/<int:item_pk>/',views.new_conversation,name='new')
]

e_platform/core_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = "core_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core_app/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')  # Add this line for the logout view
]

e_platform/dashboard/urls.py
from django.urls import path
from .import views
app_name="dashboard"

urlpatterns = [
path('', views.index, name='index'),    
    ]

e_platform/e_platform/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
     path('dashboard/',include('dashboard.urls')),
    path('',include('core_app.urls')),
    path('inbox/',include('communication.urls')),
    path('items/',include('items.urls')),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_platform/items/urls.py
from django.urls import path
from .import views

app_name='item'
urlpatterns = [
    path('',views.items_b,name='items_b'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),
    
]

e_platform/core_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your User Name','style':'background-color:#BED0FA'}))
    password= forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Your Password','style':'background-color:#BED0FA'}))





class SignupForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your User Name','style':'background-color:#BED0FA'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your E-mail','style':'background-color:#BED0FA'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Your Password','style':'background-color:#BED0FA'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Your Password','style':'background-color:#BED0FA'}))

e_platform/core_app/views.py
from django.shortcuts import render,redirect
from items.models import Category, item
from .forms import SignupForm

def index(request):
    items = item.objects.filter(is_available=True)[0:6]
    categories = Category.objects.all()
    return render(request, 'core_app/index.html', {'items': items, 'categories': categories})

def contact(request):
    return render(request, 'core_app/contact.html')

def signup(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    else:

        form=SignupForm()

    return render(request,'core_app/signup.html',{'form':form})

e_platform/core_app/templates/core_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <title>{% block title %}{% endblock %} | E_Sell</title>

    <style>
        .footer-links a:hover {
            color: #FFD700; /* Change the color on hover */
        }
    </style>
</head>
<body style="background-color:#F5F3E4">
    <nav class="navbar navbar-expand-lg navbar-light shadow-lg bg border border-success rounded-3" style="background-color:#8F43B0;">
        <a href="/" class="h1 navbar-brand shadow-lg" href="#" style="color:#EAE4E5; font-weight: 900;">E_Sell</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
               
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'item:items_b' %}" style="color:#E2E3DC">Browse</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'item:new' %}" style="color:#F6F1ED">New Item</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-primary rounded bg-info" style="color:#DFE608; font-weight: bold;" href="{% url 'communication:inbox' %}">Inbox</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link btn btn-outline-success ml-2 rounded bg-success" href="{% url 'dashboard:index' %}" style="color:#E5E510;font-weight: bold;">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-success ml-2 rounded bg-success" href="{% url 'core_app:logout' %}" style="color:#E5E510;font-weight: bold;">Log Out</a>
                        </li>
                {% else %}
                    <li class="nav-item">
                    <a class="nav-link btn btn-outline-primary rounded bg-info" style="color:#DFE608; font-weight: bold;" href="{% url 'core_app:signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link btn btn-outline-success ml-2 rounded bg-success" href="{% url 'core_app:login' %}" style="color:#E5E510;font-weight: bold;">Log In</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mt-5" style="background-color:#F5F3E4">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="py-6 px-6 shadow p-3 mb-5  text-white" style="background-color:#4c4cb0;">
        <div class="row">
            <div class="col-md-6">
                <h3 class="mb-4 font-weight-bold">About</h3>
                <p>Welcome to E-Sell, where commerce meets community. We believe in creating a platform that empowers individuals and businesses to showcase their products to a global audience.</p>
            </div>
            <div class="col-md-6">
                <h3 class="mb-4 font-weight-bold">Menu</h3>
                <ul class="list-unstyled footer-links">
                    <li><a href="#" class="text-light text-decoration-none">About</a></li>
                    <li><a href="{% url 'core_app:contact' %}" class="text-light text-decoration-none">Contact</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Privacy Policy</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Terms of Use</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <!-- Bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

e_platform/core_app/templates/core_app/contact.html
{% extends 'core_app/base.html' %}
{% block title %}Contact {% endblock %}

{% block content %} This is Contact page {% endblock%}

e_platform/core_app/templates/core_app/index.html
{% extends "core_app/base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-light rounded-xl" style="background-color:#E2DE99">
    <h2 class="mb-4 text-center display-4 border border-3 rounded " style="background-color:#EAE842" >Newest Items</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4 rounded" style="background-color:#EAE842" name="div1">
        {% for item in items %}
        <div class="col">
            <a href="{% url 'item:detail' item.id %}">
            <div class="card h-100 border-0 shadow-sm" style="background-color:#CDE45A">
                <img src="{{ item.image.url }}" class="card-img-top rounded-top" alt="{{ item.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ item.name |slice:":12" }}{% if item.name|length > 12 %}...{% endif %}</h5>

                    <p class="card-text text-muted">Price: {{ item.price }}</p>
                </div>
            </div></a>
        </div>
        {% endfor %}
    </div>
</div>

<style>
    .card:hover {
        transform: scale(1.05); /* Increase the size of the card on hover */
        transition: transform 0.3s ease; /* Add a smooth transition effect */
    }
</style>

<div class="mt-6 px-6 py-12 bg-light rounded-xl" style="margin-bottom: 20px;" name="div_cat">
    <h2 class="mb-4 text-center display-4">Categories</h2>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for category in categories %}
        <div class="col">
            <div class="card h-100 border-0 shadow-sm">
                <div class="card-body rounded" style="background-color:#4D1C7F">
                    <h5 class="card-title">{{ category.name }}</h5>
                    <p class="card-text text-muted">{{ category.items.count }} items</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

e_platform/core_app/templates/core_app/login.html
{% extends 'core_app/base.html' %}
{% block title %}Sign UP {% endblock %}
{% block content %}
<div class="container mb-4 mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card rounded">
                <div class="card-header text-center h1 text-primary">Log In</div>
                <div class="card-body" style="background-color:#F4EE8C">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.username }}
                        </div>
                        
                        <div class="mb-3">
                            {{ form.password }}
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-block mt-4">Log In</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.card:hover {
    transform: scale(1.02);
    transition: transform 0.3s;
}
</style>
{% endblock %}

e_platform/core_app/templates/core_app/signup.html
{% extends 'core_app/base.html' %}
{% block title %}Sign UP {% endblock %}
{% block content %}
<div class="container mb-4 mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card rounded">
                <div class="card-header text-center h1 text-primary">Sign Up</div>
                <div class="card-body" style="background-color:#F4EE8C">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            {{ form.email }}
                        </div>
                        <div class="mb-3">
                            {{ form.password1 }}
                        </div>
                        <div class="mb-3">
                            {{ form.password2 }}
                        </div>
                        <button type="submit" class="btn btn-primary btn-block mt-4">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
.card:hover {
    transform: scale(1.02);
    transition: transform 0.3s;
}
</style>
{% endblock %}